### PR TITLE
WIP: ICD10

### PR DESCRIPTION
**Pull request by MatthewVita**

### CODE REVIEW

**Comment by MatthewVita** [comment]
This one will be fun :)

**Comment by MatthewVita** [comment]
There doesn't appear to be an `ctakesicd2015.xml` file :(

**Comment by MatthewVita** [comment]
Okay, ripping out sno_rx and putting in the icd files gives me this. At least something is failing :)

```
Could not find org/apache/ctakes/dictionary/lookup/fast/sno_rx_16ab.xml
as absolute or in $CLASSPATH :
/apache-uima-as-2.9.0/lib/uimaj-bootstrap.jar
/apache-ctakes-4.0.0/lib/ctakes-smoking-status-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-crfsuite-2.0.0.jar
/apache-ctakes-4.0.0/lib/ant-launcher-1.9.2.jar
/apache-ctakes-4.0.0/lib/jsr305-1.3.9.jar
/apache-ctakes-4.0.0/lib/sqlwrapper-0.0.1.jar
/apache-ctakes-4.0.0/lib/lucene-sandbox-4.0.0.jar
/apache-ctakes-4.0.0/lib/uimaj-document-annotation-2.9.0.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-tksvmlight-2.0.0.jar
/apache-ctakes-4.0.0/lib/commons-cli-1.2.jar
/apache-ctakes-4.0.0/lib/websocket-servlet-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/ctakes-lvg-4.0.0.jar
/apache-ctakes-4.0.0/lib/jdom-1.0.jar
/apache-ctakes-4.0.0/lib/uimafit-core-2.2.0.jar
/apache-ctakes-4.0.0/lib/ctakes-constituency-parser-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/websocket-common-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/jsf-impl-2.1.3.jar
/apache-ctakes-4.0.0/lib/icefaces-2.0.2.jar
/apache-ctakes-4.0.0/lib/jetty-servlet-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/dom4j-1.6.1.jar
/apache-ctakes-4.0.0/lib/cxf-rt-transports-http-2.7.8.jar
/apache-ctakes-4.0.0/lib/guava-10.0.jar
/apache-ctakes-4.0.0/lib/cleartk-snowball-2.0.0.jar
/apache-ctakes-4.0.0/lib/spring-beans-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/ctakes-examples-4.0.0.jar
/apache-ctakes-4.0.0/lib/spring-tx-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/ctakes-assertion-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-token-2.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-eval-2.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-smoking-status-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/commons-io-2.2.jar
/apache-ctakes-4.0.0/lib/sbinary_2.9.0-0.4.0.jar
/apache-ctakes-4.0.0/lib/commons-el-1.0.jar
/apache-ctakes-4.0.0/lib/jsr107cache-1.0.jar
/apache-ctakes-4.0.0/lib/spring-orm-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/commons-beanutils-1.8.3.jar
/apache-ctakes-4.0.0/lib/jetty-schemas-3.1.M0.jar
/apache-ctakes-4.0.0/lib/xml-resolver-1.2.jar
/apache-ctakes-4.0.0/lib/javax.servlet.jsp.jstl-1.2.0.v201105211821.jar
/apache-ctakes-4.0.0/lib/jetty-util-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/ctakes-relation-extractor-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-clinical-pipeline-4.0.0.jar
/apache-ctakes-4.0.0/lib/jdom-2.0.2.jar
/apache-ctakes-4.0.0/lib/jchronic-0.2.6.jar
/apache-ctakes-4.0.0/lib/ctakes-constituency-parser-4.0.0.jar
/apache-ctakes-4.0.0/lib/maven-model-3.0.5.jar
/apache-ctakes-4.0.0/lib/ctakes-type-system-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-ne-contexts-4.0.0.jar
/apache-ctakes-4.0.0/lib/jetty-plus-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/ctakes-drug-ner-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-context-tokenizer-4.0.0.jar
/apache-ctakes-4.0.0/lib/javax.annotation-api-1.2.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-mallet-2.0.0.jar
/apache-ctakes-4.0.0/lib/de.tudarmstadt.ukp.dkpro.core.api.metadata-asl-1.6.0.jar
/apache-ctakes-4.0.0/lib/ctakes-core-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/jackson-mapper-asl-1.5.0.jar
/apache-ctakes-4.0.0/lib/woodstox-core-asl-4.2.0.jar
/apache-ctakes-4.0.0/lib/ctakes-gui-4.0.0.jar
/apache-ctakes-4.0.0/lib/opennlp-uima-1.7.2.jar
/apache-ctakes-4.0.0/lib/ant-1.9.2.jar
/apache-ctakes-4.0.0/lib/cglib-2.2.2.jar
/apache-ctakes-4.0.0/lib/jsf-api-2.1.3.jar
/apache-ctakes-4.0.0/lib/jetty-jndi-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/cleartk-timeml-2.0.0.jar
/apache-ctakes-4.0.0/lib/uimaj-tools-2.9.0.jar
/apache-ctakes-4.0.0/lib/ctakes-relation-extractor-4.0.0.jar
/apache-ctakes-4.0.0/lib/timenorm-0.9.5.jar
/apache-ctakes-4.0.0/lib/cxf-rt-frontend-jaxrs-2.7.8.jar
/apache-ctakes-4.0.0/lib/diffutils-1.3.0.jar
/apache-ctakes-4.0.0/lib/plexus-utils-2.0.6.jar
/apache-ctakes-4.0.0/lib/websocket-api-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/websocket-server-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/cxf-rt-ws-addr-2.7.8.jar
/apache-ctakes-4.0.0/lib/cxf-rt-frontend-simple-2.7.8.jar
/apache-ctakes-4.0.0/lib/ctakes-examples-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/opennlp-tools-1.7.2.jar
/apache-ctakes-4.0.0/lib/ehcache-core-2.4.6.jar
/apache-ctakes-4.0.0/lib/ctakes-chunker-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/commons-compress-1.4.1.jar
/apache-ctakes-4.0.0/lib/solr-commons-csv-3.5.0.jar
/apache-ctakes-4.0.0/lib/jetty-webapp-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/lucene-queries-4.0.0.jar
/apache-ctakes-4.0.0/lib/findstructapi-0.0.1.jar
/apache-ctakes-4.0.0/lib/xmlschema-core-2.0.3.jar
/apache-ctakes-4.0.0/lib/cxf-rt-bindings-soap-2.7.8.jar
/apache-ctakes-4.0.0/lib/libsvm-3.1.jar
/apache-ctakes-4.0.0/lib/lvgdist-2016.0.jar
/apache-ctakes-4.0.0/lib/jetty-http-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/commons-lang-2.6.jar
/apache-ctakes-4.0.0/lib/spring-asm-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/jetty-runner-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/ctakes-ytex-web-4.0.0-classes.jar
/apache-ctakes-4.0.0/lib/cxf-rt-databinding-aegis-2.7.8.jar
/apache-ctakes-4.0.0/lib/jregex-1.2_01.jar
/apache-ctakes-4.0.0/lib/backport-util-concurrent-3.1.jar
/apache-ctakes-4.0.0/lib/liblinear-1.94.jar
/apache-ctakes-4.0.0/lib/cleartk-type-system-2.0.0.jar
/apache-ctakes-4.0.0/lib/cxf-api-2.7.8.jar
/apache-ctakes-4.0.0/lib/wsdl4j-1.6.3.jar
/apache-ctakes-4.0.0/lib/ant-contrib-1.0b3.jar
/apache-ctakes-4.0.0/lib/jetty-security-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/ctakes-temporal-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/xz-1.0.jar
/apache-ctakes-4.0.0/lib/lucene-snowball-3.0.3.jar
/apache-ctakes-4.0.0/lib/ctakes-dictionary-lookup-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/hsqldb-2.3.4.jar
/apache-ctakes-4.0.0/lib/websocket-client-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/javax.servlet.jsp-2.3.2.jar
/apache-ctakes-4.0.0/lib/openaifsm-0.0.1.jar
/apache-ctakes-4.0.0/lib/args4j-2.0.16.jar
/apache-ctakes-4.0.0/lib/jdom2-2.0.6.jar
/apache-ctakes-4.0.0/lib/ctakes-ytex-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/icefaces-compat-2.0.2.jar
/apache-ctakes-4.0.0/lib/bsh-2.0b4.jar
/apache-ctakes-4.0.0/lib/ctakes-pos-tagger-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-feature-2.0.0.jar
/apache-ctakes-4.0.0/lib/commons-logging-api-1.1.jar
/apache-ctakes-4.0.0/lib/jaxb-impl-2.2.5.jar
/apache-ctakes-4.0.0/lib/javax.servlet.jsp-api-2.3.1.jar
/apache-ctakes-4.0.0/lib/commons-pool-1.5.4.jar
/apache-ctakes-4.0.0/lib/hppc-0.4.1.jar
/apache-ctakes-4.0.0/lib/org.eclipse.jdt.core-3.8.2.v20130121.jar
/apache-ctakes-4.0.0/lib/commons-jxpath-1.3.jar
/apache-ctakes-4.0.0/lib/ctakes-clinical-pipeline-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-side-effect-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/spring-web-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/ctakes-dictionary-lookup-fast-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-ytex-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-gui-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/spring-core-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/jetty-io-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-liblinear-2.0.0.jar
/apache-ctakes-4.0.0/lib/log4j-1.2.17.jar
/apache-ctakes-4.0.0/lib/de.tudarmstadt.ukp.dkpro.core.api.resources-asl-1.6.0.jar
/apache-ctakes-4.0.0/lib/jsp-api-2.2.jar
/apache-ctakes-4.0.0/lib/javax.servlet-api-3.1.0.jar
/apache-ctakes-4.0.0/lib/xml-apis-1.4.01.jar
/apache-ctakes-4.0.0/lib/ctakes-pos-tagger-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/jetty-xml-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/lucene-analyzers-common-4.0.0.jar
/apache-ctakes-4.0.0/lib/jstl-1.2.jar
/apache-ctakes-4.0.0/lib/uimaj-core-2.9.0.jar
/apache-ctakes-4.0.0/lib/asm-3.3.1.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-2.0.0.jar
/apache-ctakes-4.0.0/lib/lucene-core-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-dictionary-lookup-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-libsvm-2.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-coreference-4.0.0.jar
/apache-ctakes-4.0.0/lib/cxf-rt-ws-policy-2.7.8.jar
/apache-ctakes-4.0.0/lib/cxf-rt-frontend-jaxws-2.7.8.jar
/apache-ctakes-4.0.0/lib/el-impl-2.2.jar
/apache-ctakes-4.0.0/lib/org.objectweb.asm-3.1.0.v200803061910.jar
/apache-ctakes-4.0.0/lib/ctakes-dependency-parser-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/mallet-2.0.7.jar
/apache-ctakes-4.0.0/lib/trove4j-2.0.2.jar
/apache-ctakes-4.0.0/lib/spring-aop-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/antlr-2.7.7.jar
/apache-ctakes-4.0.0/lib/fast-classpath-scanner-2.0.18.jar
/apache-ctakes-4.0.0/lib/cxf-rt-core-2.7.8.jar
/apache-ctakes-4.0.0/lib/commons-dbcp-1.4.jar
/apache-ctakes-4.0.0/lib/opennlp-maxent-3.0.3.jar
/apache-ctakes-4.0.0/lib/ctakes-ne-contexts-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-util-2.0.0.jar
/apache-ctakes-4.0.0/lib/jdom-legacy-1.1.3.jar
/apache-ctakes-4.0.0/lib/cleartk-opennlp-tools-2.0.0.jar
/apache-ctakes-4.0.0/lib/jackson-core-asl-1.5.0.jar
/apache-ctakes-4.0.0/lib/org.apache.taglibs.standard.glassfish-1.2.0.v201112081803.jar
/apache-ctakes-4.0.0/lib/cxf-rt-databinding-jaxb-2.7.8.jar
/apache-ctakes-4.0.0/lib/commons-collections-3.2.1.jar
/apache-ctakes-4.0.0/lib/anti-xml_2.11-0.6.0.jar
/apache-ctakes-4.0.0/lib/neethi-3.0.2.jar
/apache-ctakes-4.0.0/lib/xercesImpl-2.11.0.jar
/apache-ctakes-4.0.0/lib/cxf-rt-bindings-xml-2.7.8.jar
/apache-ctakes-4.0.0/lib/ctakes-side-effect-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-preprocessor-4.0.0.jar
/apache-ctakes-4.0.0/lib/jetty-jaas-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/jakarta-regexp-1.4.jar
/apache-ctakes-4.0.0/lib/javax.el-3.0.0.jar
/apache-ctakes-4.0.0/lib/spring-expression-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/ctakes-temporal-4.0.0.jar
/apache-ctakes-4.0.0/lib/clearnlp-1.3.1.jar
/apache-ctakes-4.0.0/lib/aspectjweaver-1.7.3.jar
/apache-ctakes-4.0.0/lib/jetty-annotations-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/uimaj-adapter-vinci-2.9.0.jar
/apache-ctakes-4.0.0/lib/spring-jdbc-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/aopalliance-1.0.jar
/apache-ctakes-4.0.0/lib/ivy-2.3.0.jar
/apache-ctakes-4.0.0/lib/ctakes-core-4.0.0.jar
/apache-ctakes-4.0.0/lib/jetty-jsp-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/jVinci-2.9.0.jar
/apache-ctakes-4.0.0/lib/jewelcli-0.8.3.jar
/apache-ctakes-4.0.0/lib/cleartk-corpus-2.0.0.jar
/apache-ctakes-4.0.0/lib/commons-logging-1.1.1.jar
/apache-ctakes-4.0.0/lib/geronimo-javamail_1.4_spec-1.7.1.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-svmlight-2.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-coreference-res-4.0.0.jar
/apache-ctakes-4.0.0/lib/stax2-api-3.1.1.jar
/apache-ctakes-4.0.0/lib/ctakes-ytex-uima-4.0.0.jar
/apache-ctakes-4.0.0/lib/jetty-server-9.1.0.M0.jar
/apache-ctakes-4.0.0/lib/javassist-3.15.0-GA.jar
/apache-ctakes-4.0.0/lib/spring-context-3.1.2.RELEASE.jar
/apache-ctakes-4.0.0/lib/lucene-queryparser-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-drug-ner-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-chunker-4.0.0.jar
/apache-ctakes-4.0.0/lib/ctakes-utils-4.0.0.jar
/apache-ctakes-4.0.0/lib/el-api-2.2.jar
/apache-ctakes-4.0.0/lib/javax.ws.rs-api-2.0-m10.jar
/apache-ctakes-4.0.0/lib/scala-library-2.11.7.jar
/apache-ctakes-4.0.0/lib/jwi-2.2.3.jar
/apache-ctakes-4.0.0/lib/jaxb-api-2.2.5.jar
/apache-ctakes-4.0.0/lib/uimaj-cpe-2.9.0.jar
/apache-ctakes-4.0.0/lib/icefaces-ace-2.0.2.jar
/apache-ctakes-4.0.0/lib/slf4j-log4j12-1.6.1.jar
/apache-ctakes-4.0.0/lib/ctakes-dependency-parser-4.0.0.jar
/apache-ctakes-4.0.0/lib/cleartk-ml-opennlp-maxent-2.0.0.jar
/apache-ctakes-4.0.0/lib/slf4j-api-1.6.1.jar
/apache-ctakes-4.0.0/resources/
/apache-uima-as-2.9.0/examples/resources/
/apache-uima-as-2.9.0/lib/uima-core.jar
/apache-uima-as-2.9.0/lib/uimaj-as-camel.jar
/apache-uima-as-2.9.0/lib/uima-document-annotation.jar
/apache-uima-as-2.9.0/lib/uima-examples.jar
/apache-uima-as-2.9.0/lib/uima-tools.jar
/apache-uima-as-2.9.0/lib/uimaj-as-core.jar
/apache-uima-as-2.9.0/lib/uima-adapter-soap.jar
/apache-uima-as-2.9.0/lib/uima-cpe.jar
/apache-uima-as-2.9.0/lib/uimaj-as-jms.jar
/apache-uima-as-2.9.0/lib/uimaj-as-activemq.jar
/apache-uima-as-2.9.0/lib/uima-adapter-vinci.jar
/apache-uima-as-2.9.0/lib/xmlbeans.jar
/apache-uima-as-2.9.0/lib/jVinci.jar
/apache-uima-as-2.9.0/lib/jackson-core-2.4.2.jar
/apache-uima-as-2.9.0/lib/uimaj-json.jar
/apache-uima-as-2.9.0/apache-activemq/
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-camel-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/commons-logging-1.2.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-expression-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/slf4j-api-1.7.13.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-pool-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/geronimo-jms_1.1_spec-1.1.1.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-console-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-spring-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-shiro-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-kahadb-store-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-jaas-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/slf4j-log4j12-1.7.13.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-mqtt-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-partition-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/xbean-spring-3.18.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-context-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-log4j-appender-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-jms-pool-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-leveldb-store-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-aop-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/jcl-over-slf4j-1.7.13.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-amqp-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-jms-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-stomp-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-client-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/commons-pool2-2.4.2.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-runtime-config-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-broker-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/activemq-http-5.14.0.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-core-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-tx-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/hawtbuf-1.11.jar
/apache-uima-as-2.9.0/apache-activemq/lib/spring-beans-4.1.9.RELEASE.jar
/apache-uima-as-2.9.0/apache-activemq/lib/geronimo-j2ee-management_1.1_spec-1.0.1.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/commons-codec-1.9.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/xpp3-1.1.4c.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/xmlpull-1.1.3.1.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/httpclient-4.5.1.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/jetty-all-9.2.13.v20150730.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/log4j-1.2.17.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/httpcore-4.4.4.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/xstream-1.4.8.jar
/apache-uima-as-2.9.0/apache-activemq/lib/optional/geronimo-servlet_3.0_spec-1.0.jar
or in working directory : /
or in any parent thereof (with or without /ctakes/)
or in $CTAKES_HOME : /apache-ctakes-4.0.0
org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/apache-ctakes-4.0.0/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
	at org.apache.uima.aae.controller.PrimitiveAnalysisEngineController_impl.initializeAnalysisEngine(PrimitiveAnalysisEngineController_impl.java:376)
	at org.apache.uima.aae.UimaAsThreadFactory$1.run(UimaAsThreadFactory.java:120)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.uima.resource.ResourceInitializationException: Initialization of annotator class "org.apache.ctakes.dictionary.lookup2.ae.DefaultJCasTermAnnotator" failed.  (Descriptor: file:/apache-ctakes-4.0.0/desc/ctakes-dictionary-lookup-fast/desc/analysis_engine/UmlsLookupAnnotator.xml)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:271)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initialize(PrimitiveAnalysisEngine_impl.java:170)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.analysis_engine.asb.impl.ASB_impl.setup(ASB_impl.java:256)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initASB(AggregateAnalysisEngine_impl.java:429)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initializeAggregateAnalysisEngine(AggregateAnalysisEngine_impl.java:373)
	at org.apache.uima.analysis_engine.impl.AggregateAnalysisEngine_impl.initialize(AggregateAnalysisEngine_impl.java:186)
	at org.apache.uima.impl.AnalysisEngineFactory_impl.produceResource(AnalysisEngineFactory_impl.java:94)
	at org.apache.uima.impl.CompositeResourceFactory_impl.produceResource(CompositeResourceFactory_impl.java:62)
	at org.apache.uima.UIMAFramework.produceResource(UIMAFramework.java:279)
	at org.apache.uima.UIMAFramework.produceAnalysisEngine(UIMAFramework.java:407)
	at org.apache.uima.aae.controller.PrimitiveAnalysisEngineController_impl.initializeAnalysisEngine(PrimitiveAnalysisEngineController_impl.java:265)
	... 2 more
Caused by: org.apache.uima.resource.ResourceInitializationException
	at org.apache.ctakes.dictionary.lookup2.ae.AbstractJCasTermAnnotator.initialize(AbstractJCasTermAnnotator.java:131)
	at org.apache.uima.analysis_engine.impl.PrimitiveAnalysisEngine_impl.initializeAnalysisComponent(PrimitiveAnalysisEngine_impl.java:266)
	... 16 more
Caused by: java.io.FileNotFoundException: No File exists at org/apache/ctakes/dictionary/lookup/fast/sno_rx_16ab.xml
	at org.apache.ctakes.core.resource.FileLocator.getFullPath(FileLocator.java:193)
	at org.apache.ctakes.core.resource.FileLocator.locateFile(FileLocator.java:99)
	at org.apache.ctakes.core.resource.FileLocator.getAsStream(FileLocator.java:73)
	at org.apache.ctakes.core.resource.FileLocator.getAsStream(FileLocator.java:53)
	at org.apache.ctakes.dictionary.lookup2.ae.AbstractJCasTermAnnotator.initialize(AbstractJCasTermAnnotator.java:128)
	... 17 more

```

**Comment by tmills** [comment]
This is the error you see if ctakes can't find your Dictionary descriptor file. To use a new dictionary, you need to point the UIMA descriptor file at a new Dictionary descriptor file (contains settings for dictionary path and type), and the dictionary descriptor file needs to be on the classpath.

**Comment by MatthewVita** [comment]
Hi @tmills,

It looks like cTAKES is pretty much coupled to Snomed/Rxnorm by default so I'm just leaving them in there.

It's interesting because if you look at how the dictionary is formed it looks like this:

```
- sno_rx_16ab.xml
  - sno_rx_16ab
    - sno_rx_16ab.properties
    - sno_rx_16ab.script
```

However, when it comes to ICD10, the structure is like this:

```
- ctakesicd2015.properties
- ctakesicd2015.script
```

I have tried to force a similar structure by creating the docker container like so:

```
RUN wget https://sourceforge.net/p/ctakesresources/code/HEAD/tree/trunk/ctakes-resources-snomed-rword-hsqldb-2011ab/src/main/resources/org/apache/ctakes/dictionary/lookup/fast/ctakesicd2015/ctakesicd2015.properties

RUN wget https://sourceforge.net/p/ctakesresources/code/HEAD/tree/trunk/ctakes-resources-snomed-rword-hsqldb-2011ab/src/main/resources/org/apache/ctakes/dictionary/lookup/fast/ctakesicd2015/ctakesicd2015.script

RUN mkdir apache-ctakes-4.0.0/resources/org/apache/ctakes/dictionary/lookup/fast/ctakesicd2015

RUN cp ctakesicd2015* apache-ctakes-4.0.0/resources/org/apache/ctakes/dictionary/lookup/fast/

RUN cp ctakesicd2015* apache-ctakes-4.0.0/resources/org/apache/ctakes/dictionary/lookup/fast/ctakesicd2015
```

However, it really appears that that it's missing an XML manifest like the Snomed/Rxnorm one. Is this the `Dictionary descriptor file` that you mentioned?

**Comment by MatthewVita** [comment]
Of course, I don't want to invent and wheels. Do you know of anyone in the community that I can reach out to that may have the `ctakesicd2015.xml` file?

**Comment by tmills** [comment]
Yeah it looks like that's what's missing. I would try sending a message to
the ctakes-dev list and see if anyone knows who is responsible for that
file in sourceforge and whether they have a dictionary descriptor for it.
https://ctakes.apache.org/mailing-lists.html

**Comment by MatthewVita** [comment]
You are the best. Thanks!

**Comment by MatthewVita** [comment]
Closing in favor of https://github.com/tmills/ctakes-docker/pull/17

**Pull request closed without merging**
